// export const baseUrl = "https://dev.fitsolscs.com/api/v1";

export const baseUrl = "http://localhost:3001/api/v1"


export const travelModeOptions = [
    "Scooter <110CC",
    "Scooter <150CC",
    "Small Car <800CC_LPG",
    "Motorcycle <100CC",
    "Motorcycle <125CC",
    "Motorcycle <135CC",
    "Motorcycle <200CC",
    "Motorcycle <300CC",
    "Motorcycle <500CC",
    "Three Wheeler_Petrol",
    "Three Wheeler_Diesel",
    "Three Wheeler_CNG",
    "Small Car <800CC _Gasoline",
    "Small Car <800CC_CNG",
    "Hatchback <1600CC_Diesel",
    "Sedan <1400CC_Diesel",
    "Sedan <1600CC_Diesel",
    "Sedan <2000CC_Diesel",
    "Premium Sedan <2000CC_Diesel",
    "Premium Sedan <2500CC_Diesel",
    "Premium Sedan <3000CC_Diesel",
    "MUV <1400CC_Diesel",
    "MUV <2500CC_Diesel",
    "Hatchback Car <1000CC_Gasoline",
    "Hatchback Car <1400CC_Gasoline",
    "Compact SUV <1600CC_Gasoline",
    "Premium Hatchback Car <1600CC_Gasoline",
    "Gypsy_1298CC_Gasoline",
    "Sedan <1400CC_Gasoline",
    "Sedan <1600CC_Gasoline",
    "Sedan <2500CC_Gasoline",
    "Sedan <2000CC_Gasoline",
    "SUV <2000CC_Gasoline",
    "MUV <3000CC_Gasoline",
    "Premium SUV <2000CC_Gasoline",
    "Premium SUV <3000CC_Gasoline",
    "Premium SUV >3000CC_Gasoline",
    "Premium Sedan <3000CC_Gasoline",
    "Premium Sedan <2000CC_Gasoline",
    "Premium Sedan >3000CC_Gasoline",
    "Hybrid <2000CC_Gasoline",
    "Hatchback <1000CC_Diesel",
    "Bus",
    "Aircraft",
    "Maxi Van_Diesel",
    "SUV <2000CC_Diesel",
    "SUV <2500CC_Diesel",
    "SUV <3000CC_Diesel",
    "Premium SUV <2000CC_Diesel",
    "Premium SUV <3000CC_Diesel",
    "Indian_NonSuburban_Railways",
    "Indian_Suburban_Railways",
    "Indian_Metro",
    "Hatchback <1400CC_Diesel",
    "Premium SUV >3000CC_Diesel",
    "Premium SUV <2500CC_Diesel",
  ];

export const designations = [
    "CEO",
    "CTO",
    "CBO",
    "CFO",
    "COO",
    "Software Engineer",
    "Project Manager",
    "Product Manager",
    "Sales Manager",
    "Marketing Specialist",
    "HR Manager",
    "Finance Manager",
    "Operations Manager",
    "Consultant",
    "Analyst",
    "Others",
  ];


